services:
  storage-location-db:
    image: postgres:15
    container_name: storage-location-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: storage_location_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - storage_location_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d storage_location_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  storage_location_postgres_data:
